#include <stdexcept>
#include <thread>
#include <sys/epoll.h>

#include "StorageConfig.h"
#include "ZvejysServer.h"
#include "backend/include/ptsouchlos_thread-pool/thread_pool.h"
#include "env/EnvConfig.h"
#include "routes/health-route/HealthRoutes.h"
#include "routes/segments-route/SegmentsRoutes.h"
#include "./include/ptsouchlos_thread-pool/thread_pool.h"
const int MAX_EVENT_BATCH = 64; // Maximum number of epoll events to process in one batch
int threadPoolSize = std::thread::hardware_concurrency() * 2;
static dp::thread_pool appThreadPool(threadPoolSize);
CorsConfig corsConfig{
    .allowed_origins = {"https://localhost:3000", "https://localhost:5173", "https://169.254.83.107:5173"},
    .allow_credentials = true,
    .allowed_methods = {"GET", "POST", "PUT", "DELETE", "OPTIONS"},
    .allowed_headers = {"Content-Type", "Authorization"},
    .max_age_seconds = 86400 // 24 hours
};

int CreateEpoll()
{
    int epoll_fd = epoll_create1(0);
    if (epoll_fd < 0)
    {
        throw std::runtime_error("Failed to create epoll instance");
    }

    return epoll_fd;
}

void AddToEpoll(int epollFD, int fd)
{
    struct epoll_event event;
    event.data.fd = fd;
    event.events = EPOLLIN | EPOLLET; // Edge-triggered read events
    epoll_ctl(epollFD, EPOLL_CTL_ADD, fd, &event);
}

[[noreturn]] int main()
{
    StorageConfig::Init();
    
    // Cleanup thread — delete stream directories older than 6 hours
    std::thread cleanupThread([]() {
        const auto maxAge = std::chrono::hours(6);

        while (true) {
            std::this_thread::sleep_for(std::chrono::minutes(10));

            try {
                std::string baseDir = StorageConfig::BaseDir();
                if (!std::filesystem::exists(baseDir)) continue;

                auto now = std::filesystem::file_time_type::clock::now();

                for (auto& entry : std::filesystem::directory_iterator(baseDir)) {
                    if (!entry.is_directory()) continue;

                    // Check the most recent file in the directory
                    auto newest = std::filesystem::file_time_type::min();
                    for (auto& file : std::filesystem::directory_iterator(entry.path())) {
                        auto mod = std::filesystem::last_write_time(file);
                        if (mod > newest) newest = mod;
                    }

                    if (newest == std::filesystem::file_time_type::min()) {
                        // Empty directory — delete it
                        std::filesystem::remove_all(entry.path());
                        std::cout << "[Cleanup] Removed empty: " << entry.path().filename() << std::endl;
                    } else if ((now - newest) > maxAge) {
                        std::filesystem::remove_all(entry.path());
                        std::cout << "[Cleanup] Expired: " << entry.path().filename() << std::endl;
                    }
                }
            } catch (const std::exception& e) {
                std::cerr << "[Cleanup] Error: " << e.what() << std::endl;
            }
        }
    });
    cleanupThread.detach();


    auto& env = EnvConfig::Instance();
    env.Load(std::string(PROJECT_ROOT) + "/.env");

    int epoll_fd = CreateEpoll();

    // -- Setup http rest server
    std::string serverHost = env.Get("STREAM_POCKET_SERVER_HOST", "127.0.0.1");
    int serverPort = std::stoi(env.Get("STREAM_POCKET_SERVER_PORT", "7070"));

    ZvejysServer httpServer(serverHost, serverPort, corsConfig, nullptr);
    int httpServerSocketFD = httpServer.GetSocketFD();
    httpServer.Start();
    RegisterHealthRoutes(httpServer);
    RegisterSegmentRoutes(httpServer);
    httpServer.DebugHttpRoutes();

    AddToEpoll(epoll_fd, httpServerSocketFD);
    struct epoll_event ready_events[MAX_EVENT_BATCH];

    while (true)
    {
        int nfds = epoll_wait(epoll_fd, ready_events, MAX_EVENT_BATCH, -1);
        for (int i = 0; i < nfds; i++)
        {
            epoll_event& event = ready_events[i];

            if (event.data.fd == httpServerSocketFD)
            {
                // new connection
                httpServer.HandleEpollNewConnection(epoll_fd, event);
                std::cout << "I just accepted a new connection" << std::endl;
            }
            else
            {
                auto raw_conn = static_cast<Connection*>(event.data.ptr);

                std::shared_ptr<Connection> safe_conn = raw_conn->shared_from_this();
                if (event.events & EPOLLIN)
                {
                    safe_conn->OnReadable();
                }

                // Write second so any response generated by the read gets sent out immediately
                if (event.events & EPOLLOUT)
                {
                    safe_conn->OnWritable(epoll_fd);
                }

                if ((event.events & (EPOLLHUP | EPOLLERR)) && !(event.events & EPOLLIN))
                {
                    // Build a fake epoll_event for the existing API
                    epoll_event ev{};
                    ev.data.ptr = safe_conn.get();
                    httpServer.HandleClientClosedConnection(ev);
                }
                // appThreadPool.enqueue_detach([safe_conn, epoll_fd, events = event.events, &httpServer]()
                // {
                //     // Read first to parse the request and generate the response
                //     if (events & EPOLLIN)
                //     {
                //         safe_conn->OnReadable();
                //     }
                //
                //     // Write second so any response generated by the read gets sent out immediately
                //     if (events & EPOLLOUT)
                //     {
                //         safe_conn->OnWritable(epoll_fd);
                //     }
                //
                //     if ((events & (EPOLLHUP | EPOLLERR)) && !(events & EPOLLIN))
                //     {
                //         // Build a fake epoll_event for the existing API
                //         epoll_event ev{};
                //         ev.data.ptr = safe_conn.get();
                //         httpServer.HandleClientClosedConnection(ev);
                //     }
                // });
            }
        }
    }
}
